version: '3.8'

services:

  portfolio-frontend:
    image: ghcr.io/sameerpathania1/portfolio-frontend:latest
    container_name: portfolio-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  portfolio-backend:
    image: ghcr.io/sameerpathania1/portfolio-backend:latest
    container_name: portfolio-backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  app-network:
    driver: bridge