version: '3.8'

services:

  portfolio-frontend:
    image: ghcr.io/sameerpathania1/portfolio-frontend:latest
    container_name: portfolio-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      
  portfolio-backend:
    image: ghcr.io/sameerpathania1/portfolio-backend:latest
    container_name: portfolio-backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production