version: '3.8'

services:

  portfolio-frontend:
    image: ghcr.io/sameerpathania1/portfolio-frontend:latest
    container_name: portfolio-frontend
    restart: always
    expose:
      - "3000"
    depends_on:
      - portfolio-backend

  portfolio-backend:
    image: ghcr.io/sameerpathania1/portfolio-backend:latest
    container_name: portfolio-backend
    restart: always
    expose:
      - "3001"
    environment:
      - NODE_ENV=production