version: '3.8'

services:
  portfolio-backend:
    image: ghcr.io/sameerpathania1/portfolio-backend:latest
    container_name: portfolio-backend
    expose:
      - "3000"
    environment:
      - NODE_ENV=production

  portfolio-frontend:
    image: ghcr.io/sameerpathania1/portfolio-frontend:latest
    container_name: portfolio-frontend
    expose:
      - "80"
    depends_on:
      - portfolio-backend